# Generated by Django 5.1.4 on 2024-12-25 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_otp_customuser_alter_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
